// Turns the icon *name* stored on a Feature row into a real lucide component.
//
// Only the icons the seed actually uses are listed, so the bundle never pulls in
// the whole icon set. Add a line here when you add an icon name to the seed.

import {
  Building2,
  CheckCircle2,
  Clock,
  FileText,
  Globe2,
  GraduationCap,
  Handshake,
  HeartPulse,
  LifeBuoy,
  Mail,
  MapPin,
  MessageCircle,
  Phone,
  PhoneCall,
  Send,
  Sparkles,
  Store,
  TrendingUp,
  UserCheck,
  Users,
  Wallet,
  CalendarCheck,
  CreditCard,
  Gauge,
  Headset,
  Home,
  Laptop,
  Network,
  Repeat,
  Router,
  Server,
  ShieldCheck,
  Signal,
  Smartphone,
  Truck,
  Tv,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  Building2,
  CheckCircle2,
  Clock,
  FileText,
  Globe2,
  GraduationCap,
  Handshake,
  HeartPulse,
  LifeBuoy,
  Mail,
  MapPin,
  MessageCircle,
  Phone,
  PhoneCall,
  Send,
  Sparkles,
  Store,
  TrendingUp,
  UserCheck,
  Users,
  Wallet,
  CalendarCheck,
  CreditCard,
  Gauge,
  Headset,
  Home,
  Laptop,
  Network,
  Repeat,
  Router,
  Server,
  ShieldCheck,
  Signal,
  Smartphone,
  Truck,
  Tv,
  Wifi,
  Wrench,
  Zap,
};

/** Falls back to a neutral icon when a name is missing or unknown. */
export function iconFor(name: string | null | undefined): LucideIcon {
  return (name && icons[name]) || Sparkles;
}
